# Generated by Django 5.0.6 on 2024-06-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_newscategorymodel_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategorymodel',
            options={'verbose_name': 'NewsCategory', 'verbose_name_plural': 'NewsCategories'},
        ),
    ]
